#!/bin/bash

[ $# -lt 1 ] && exit

user=`who am i |cut -f1 -d" "`

while [ $# -ne 0 ]
do
	res=`./proc "$user" | awk " \\\$3 ~ /^$1\$/ { print \\\$1 } "`

	[ -z "$res" ] && echo "no cmd find own by u" && exit

	line=`echo "$res"| wc -l`

	[ $line -eq 1 ] && kill "$res" && shift && continue

	echo "which $1 ?"
	select line in $res '*'
	do 
		[ -z $line ] && continue
		echo "u select $line"
		[ '*' = "$line" ] && kill $res && break
		kill "$line"
		break
	done
	shift
done
